package com.ccz.app.campaign

import com.ccz.core.model.Faction

internal data class PromotedStageExpectation(
    val runtime: BundledBattleRuntime,
    val initialUnits: Int,
    val enemies: Int,
    val allies: Int,
    val width: Int,
    val height: Int,
    val deferred: Int = 0,
    val protectUnits: List<String> = listOf("hero_1"),
    val minTerrainKinds: Int = 2,
) {
    val stageId: String = runtime.stageId
    val factions: Set<Faction> = buildSet {
        add(Faction.PLAYER)
        if (allies > 0) add(Faction.ALLY)
        if (enemies > 0) add(Faction.ENEMY)
    }
}

internal object PromotedStageExpectations {
    val all: List<PromotedStageExpectation> = listOf(
        stage("legacy_stage_2", initialUnits = 43, enemies = 29, allies = 11, width = 21, height = 20),
        stage("legacy_stage_3", initialUnits = 72, enemies = 51, allies = 18, width = 28, height = 24),
        stage("legacy_stage_4", initialUnits = 52, enemies = 39, allies = 10, width = 19, height = 20),
        stage("legacy_stage_5", initialUnits = 66, enemies = 49, allies = 14, width = 20, height = 28),
        stage("legacy_stage_6", initialUnits = 58, enemies = 40, allies = 15, width = 35, height = 16),
        stage("legacy_stage_8", initialUnits = 70, enemies = 53, allies = 14, width = 22, height = 21, deferred = 1),
        stage("legacy_stage_9", initialUnits = 46, enemies = 43, allies = 0, width = 24, height = 20),
        stage("legacy_stage_10", initialUnits = 92, enemies = 78, allies = 11, width = 24, height = 20),
        stage("legacy_stage_11", initialUnits = 47, enemies = 44, allies = 0, width = 24, height = 28),
        stage("legacy_stage_12", initialUnits = 78, enemies = 71, allies = 4, width = 24, height = 20),
        stage("legacy_stage_13", initialUnits = 65, enemies = 59, allies = 3, width = 36, height = 16),
        stage("legacy_stage_14", initialUnits = 96, enemies = 79, allies = 14, width = 24, height = 28),
        stage("legacy_stage_16", initialUnits = 38, enemies = 32, allies = 3, width = 28, height = 20),
        stage("legacy_stage_17", initialUnits = 42, enemies = 33, allies = 6, width = 22, height = 20),
        stage("legacy_stage_18", initialUnits = 70, enemies = 59, allies = 8, width = 26, height = 30),
        stage("legacy_stage_19", initialUnits = 23, enemies = 20, allies = 0, width = 22, height = 18),
        stage(
            "legacy_stage_21",
            initialUnits = 27,
            enemies = 24,
            allies = 0,
            width = 20,
            height = 30,
            protectUnits = listOf("hero_3"),
        ),
        stage(
            "legacy_stage_23",
            initialUnits = 51,
            enemies = 36,
            allies = 12,
            width = 22,
            height = 24,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_24", initialUnits = 52, enemies = 39, allies = 10, width = 20, height = 35),
        stage("legacy_stage_29", initialUnits = 61, enemies = 58, allies = 0, width = 40, height = 24),
        stage("legacy_stage_30", initialUnits = 81, enemies = 78, allies = 0, width = 33, height = 34),
        stage("legacy_stage_31", initialUnits = 30, enemies = 25, allies = 2, width = 24, height = 20),
        stage("legacy_stage_34", initialUnits = 50, enemies = 39, allies = 8, width = 24, height = 36),
        stage("legacy_stage_35", initialUnits = 60, enemies = 57, allies = 0, width = 24, height = 34),
        stage("legacy_stage_36", initialUnits = 22, enemies = 19, allies = 0, width = 24, height = 28),
        stage("legacy_stage_37", initialUnits = 55, enemies = 52, allies = 0, width = 32, height = 20),
        stage("legacy_stage_38", initialUnits = 45, enemies = 42, allies = 0, width = 20, height = 26),
        stage(
            "legacy_stage_39",
            initialUnits = 42,
            enemies = 39,
            allies = 0,
            width = 24,
            height = 20,
            protectUnits = listOf("hero_3"),
        ),
        stage("legacy_stage_40", initialUnits = 37, enemies = 32, allies = 2, width = 28, height = 22),
        stage(
            "legacy_stage_41",
            initialUnits = 63,
            enemies = 47,
            allies = 13,
            width = 28,
            height = 26,
            protectUnits = listOf("hero_1", "hero_77"),
        ),
        stage("legacy_stage_42", initialUnits = 58, enemies = 50, allies = 5, width = 20, height = 32),
        stage("legacy_stage_44", initialUnits = 38, enemies = 33, allies = 2, width = 20, height = 25),
        stage("legacy_stage_45", initialUnits = 27, enemies = 24, allies = 0, width = 19, height = 28),
        stage("legacy_stage_46", initialUnits = 63, enemies = 58, allies = 2, width = 34, height = 24),
        stage("legacy_stage_47", initialUnits = 50, enemies = 47, allies = 0, width = 22, height = 25),
        stage("legacy_stage_48", initialUnits = 41, enemies = 38, allies = 0, width = 20, height = 20),
        stage("legacy_stage_50", initialUnits = 72, enemies = 67, allies = 2, width = 20, height = 24),
        stage(
            "legacy_stage_51",
            initialUnits = 59,
            enemies = 53,
            allies = 3,
            width = 32,
            height = 18,
            protectUnits = listOf("hero_1", "hero_3"),
        ),
        stage(
            "legacy_stage_52",
            initialUnits = 55,
            enemies = 52,
            allies = 0,
            width = 20,
            height = 24,
            protectUnits = listOf("hero_3"),
        ),
        stage(
            "legacy_stage_53",
            initialUnits = 46,
            enemies = 42,
            allies = 1,
            width = 18,
            height = 24,
            protectUnits = listOf("hero_3"),
        ),
        stage("legacy_stage_54", initialUnits = 75, enemies = 69, allies = 3, width = 30, height = 31),
        stage("legacy_stage_55", initialUnits = 70, enemies = 58, allies = 9, width = 20, height = 30),
        stage("legacy_stage_56", initialUnits = 81, enemies = 78, allies = 0, width = 32, height = 28),
        stage(
            "legacy_stage_57",
            initialUnits = 79,
            enemies = 76,
            allies = 0,
            width = 28,
            height = 24,
            protectUnits = listOf("hero_1", "hero_3"),
        ),
        stage(
            "legacy_stage_58",
            initialUnits = 44,
            enemies = 41,
            allies = 0,
            width = 18,
            height = 24,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_59",
            initialUnits = 40,
            enemies = 37,
            allies = 0,
            width = 24,
            height = 22,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_61", initialUnits = 68, enemies = 64, allies = 1, width = 21, height = 28),
        stage("legacy_stage_62", initialUnits = 68, enemies = 65, allies = 0, width = 28, height = 24),
        stage("legacy_stage_64", initialUnits = 73, enemies = 64, allies = 6, width = 22, height = 32),
        stage("legacy_stage_66", initialUnits = 50, enemies = 44, allies = 3, width = 34, height = 20),
        stage("legacy_stage_69", initialUnits = 73, enemies = 70, allies = 0, width = 30, height = 30),
        stage("legacy_stage_70", initialUnits = 83, enemies = 80, allies = 0, width = 26, height = 27),
        stage("legacy_stage_72", initialUnits = 83, enemies = 80, allies = 0, width = 40, height = 33),
        stage("legacy_stage_73", initialUnits = 49, enemies = 46, allies = 0, width = 28, height = 22),
        stage("legacy_stage_76", initialUnits = 52, enemies = 40, allies = 9, width = 20, height = 30),
        stage("legacy_stage_77", initialUnits = 50, enemies = 47, allies = 0, width = 26, height = 18),
        stage("legacy_stage_78", initialUnits = 68, enemies = 62, allies = 3, width = 24, height = 20),
        stage("legacy_stage_83", initialUnits = 92, enemies = 78, allies = 11, width = 22, height = 28),
        stage("legacy_stage_86", initialUnits = 99, enemies = 79, allies = 17, width = 26, height = 30),
        stage("legacy_stage_89", initialUnits = 4, enemies = 1, allies = 0, width = 15, height = 15, minTerrainKinds = 1),
        stage("legacy_stage_91", initialUnits = 65, enemies = 58, allies = 4, width = 26, height = 28),
        stage("legacy_stage_93", initialUnits = 28, enemies = 25, allies = 0, width = 19, height = 21),
        stage("legacy_stage_94", initialUnits = 48, enemies = 45, allies = 0, width = 19, height = 23),
        stage("legacy_stage_95", initialUnits = 65, enemies = 60, allies = 2, width = 32, height = 20),
        stage("legacy_stage_96", initialUnits = 73, enemies = 70, allies = 0, width = 29, height = 27),
        stage("legacy_stage_97", initialUnits = 12, enemies = 9, allies = 0, width = 28, height = 24),
        stage("legacy_stage_99", initialUnits = 55, enemies = 52, allies = 0, width = 19, height = 28),
        stage("legacy_stage_101", initialUnits = 12, enemies = 1, allies = 8, width = 20, height = 15),
        stage("legacy_stage_102", initialUnits = 16, enemies = 13, allies = 0, width = 20, height = 10),
        stage(
            "legacy_stage_103",
            initialUnits = 12,
            enemies = 9,
            allies = 0,
            width = 20,
            height = 20,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_104",
            initialUnits = 24,
            enemies = 12,
            allies = 9,
            width = 28,
            height = 34,
            protectUnits = listOf("hero_3"),
        ),
        stage("legacy_stage_105", initialUnits = 43, enemies = 40, allies = 0, width = 28, height = 24),
        stage("legacy_stage_107", initialUnits = 31, enemies = 28, allies = 0, width = 36, height = 18),
        stage("legacy_stage_109", initialUnits = 19, enemies = 14, allies = 2, width = 26, height = 27),
        stage("legacy_stage_111", initialUnits = 15, enemies = 12, allies = 0, width = 34, height = 32),
        stage("legacy_stage_112", initialUnits = 19, enemies = 16, allies = 0, width = 30, height = 23),
        stage("legacy_stage_114", initialUnits = 23, enemies = 16, allies = 4, width = 26, height = 30),
        stage(
            "legacy_stage_115",
            initialUnits = 81,
            enemies = 78,
            allies = 0,
            width = 32,
            height = 27,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_116",
            initialUnits = 81,
            enemies = 78,
            allies = 0,
            width = 40,
            height = 33,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_119", initialUnits = 83, enemies = 80, allies = 0, width = 40, height = 40),
        stage("legacy_stage_120", initialUnits = 49, enemies = 46, allies = 0, width = 40, height = 40),
        stage("legacy_stage_122", initialUnits = 83, enemies = 80, allies = 0, width = 40, height = 40),
        stage("legacy_stage_127", initialUnits = 66, enemies = 63, allies = 0, width = 30, height = 30),
        stage("legacy_stage_128", initialUnits = 14, enemies = 11, allies = 0, width = 24, height = 30),
        stage("legacy_stage_130", initialUnits = 31, enemies = 28, allies = 0, width = 24, height = 24),
        stage("legacy_stage_131", initialUnits = 23, enemies = 20, allies = 0, width = 36, height = 32),
        stage("legacy_stage_134", initialUnits = 47, enemies = 44, allies = 0, width = 31, height = 25),
        stage("legacy_stage_135", initialUnits = 30, enemies = 26, allies = 1, width = 40, height = 29),
        stage("legacy_stage_136", initialUnits = 57, enemies = 54, allies = 0, width = 35, height = 24),
        stage("legacy_stage_137", initialUnits = 73, enemies = 70, allies = 0, width = 28, height = 22),
        stage("legacy_stage_141", initialUnits = 33, enemies = 30, allies = 0, width = 25, height = 25),
        stage("legacy_stage_143", initialUnits = 78, enemies = 75, allies = 0, width = 40, height = 35),
        stage("legacy_stage_144", initialUnits = 43, enemies = 40, allies = 0, width = 40, height = 40),
        stage("legacy_stage_145", initialUnits = 26, enemies = 23, allies = 0, width = 40, height = 40),
        stage("legacy_stage_146", initialUnits = 46, enemies = 43, allies = 0, width = 30, height = 30),
        stage("legacy_stage_147", initialUnits = 68, enemies = 65, allies = 0, width = 40, height = 40),
        stage("legacy_stage_148", initialUnits = 72, enemies = 69, allies = 0, width = 32, height = 17),
        stage("legacy_stage_152", initialUnits = 73, enemies = 70, allies = 0, width = 40, height = 40),
        stage("legacy_stage_156", initialUnits = 14, enemies = 11, allies = 0, width = 28, height = 36),
        stage("legacy_stage_157", initialUnits = 19, enemies = 16, allies = 0, width = 18, height = 25),
        stage("legacy_stage_158", initialUnits = 27, enemies = 24, allies = 0, width = 22, height = 28),
        stage("legacy_stage_165", initialUnits = 23, enemies = 20, allies = 0, width = 30, height = 19),
        stage("legacy_stage_172", initialUnits = 54, enemies = 51, allies = 0, width = 32, height = 20),
        stage("legacy_stage_174", initialUnits = 15, enemies = 12, allies = 0, width = 24, height = 28),
        stage("legacy_stage_175", initialUnits = 15, enemies = 12, allies = 0, width = 24, height = 24),
        stage("legacy_stage_176", initialUnits = 48, enemies = 45, allies = 0, width = 32, height = 40),
        stage("legacy_stage_178", initialUnits = 78, enemies = 75, allies = 0, width = 24, height = 40),
        stage("legacy_stage_179", initialUnits = 5, enemies = 1, allies = 1, width = 28, height = 36),
        stage("legacy_stage_180", initialUnits = 21, enemies = 17, allies = 1, width = 32, height = 40),
        stage("legacy_stage_182", initialUnits = 9, enemies = 6, allies = 0, width = 36, height = 32),
        stage("legacy_stage_186", initialUnits = 11, enemies = 7, allies = 1, width = 28, height = 16),
        stage("legacy_stage_189", initialUnits = 35, enemies = 32, allies = 0, width = 25, height = 25),
        stage("legacy_stage_194", initialUnits = 24, enemies = 21, allies = 0, width = 37, height = 24),
        stage("legacy_stage_196", initialUnits = 6, enemies = 3, allies = 0, width = 30, height = 20),
        stage("legacy_stage_197", initialUnits = 23, enemies = 19, allies = 1, width = 20, height = 31),
        stage("legacy_stage_201", initialUnits = 7, enemies = 4, allies = 0, width = 32, height = 34),
        stage("legacy_stage_202", initialUnits = 16, enemies = 10, allies = 3, width = 40, height = 40),
        stage("legacy_stage_204", initialUnits = 9, enemies = 6, allies = 0, width = 25, height = 20),
        stage("legacy_stage_205", initialUnits = 8, enemies = 5, allies = 0, width = 20, height = 25),
        stage("legacy_stage_206", initialUnits = 22, enemies = 10, allies = 9, width = 30, height = 20),
        stage("legacy_stage_207", initialUnits = 22, enemies = 10, allies = 9, width = 20, height = 25),
        stage("legacy_stage_209", initialUnits = 19, enemies = 5, allies = 11, width = 40, height = 24),
        stage("legacy_stage_210", initialUnits = 9, enemies = 4, allies = 2, width = 31, height = 30),
        stage("legacy_stage_214", initialUnits = 11, enemies = 8, allies = 0, width = 24, height = 36),
        stage("legacy_stage_215", initialUnits = 11, enemies = 8, allies = 0, width = 30, height = 36),
        stage("legacy_stage_216", initialUnits = 24, enemies = 10, allies = 11, width = 40, height = 40),
        stage("legacy_stage_217", initialUnits = 23, enemies = 18, allies = 2, width = 17, height = 21),
        stage("legacy_stage_218", initialUnits = 23, enemies = 20, allies = 0, width = 19, height = 19),
        stage("legacy_stage_219", initialUnits = 25, enemies = 16, allies = 6, width = 27, height = 36),
        stage("legacy_stage_220", initialUnits = 19, enemies = 16, allies = 0, width = 16, height = 18),
        stage(
            "legacy_stage_221",
            initialUnits = 23,
            enemies = 20,
            allies = 0,
            width = 16,
            height = 18,
            minTerrainKinds = 1,
        ),
        stage("legacy_stage_222", initialUnits = 25, enemies = 22, allies = 0, width = 16, height = 18),
        stage("legacy_stage_224", initialUnits = 4, enemies = 1, allies = 0, width = 27, height = 20),
        stage("legacy_stage_225", initialUnits = 5, enemies = 2, allies = 0, width = 36, height = 24),
        stage("legacy_stage_226", initialUnits = 21, enemies = 5, allies = 13, width = 40, height = 40),
        stage("legacy_stage_227", initialUnits = 33, enemies = 30, allies = 0, width = 30, height = 35),
        stage("legacy_stage_228", initialUnits = 36, enemies = 33, allies = 0, width = 29, height = 22),
        stage("legacy_stage_229", initialUnits = 27, enemies = 22, allies = 2, width = 40, height = 35),
        stage("legacy_stage_230", initialUnits = 9, enemies = 6, allies = 0, width = 36, height = 36),
        stage(
            "legacy_stage_231",
            initialUnits = 21,
            enemies = 8,
            allies = 10,
            width = 23,
            height = 40,
            protectUnits = listOf("hero_3147", "hero_1"),
        ),
        stage("legacy_stage_233", initialUnits = 8, enemies = 4, allies = 1, width = 26, height = 32),
        stage("legacy_stage_234", initialUnits = 23, enemies = 20, allies = 0, width = 35, height = 16),
        stage("legacy_stage_235", initialUnits = 13, enemies = 10, allies = 0, width = 18, height = 21),
        stage("legacy_stage_236", initialUnits = 44, enemies = 41, allies = 0, width = 22, height = 30),
        stage("legacy_stage_237", initialUnits = 7, enemies = 4, allies = 0, width = 40, height = 22),
        stage("legacy_stage_239", initialUnits = 9, enemies = 5, allies = 1, width = 28, height = 30),
        stage("legacy_stage_242", initialUnits = 37, enemies = 25, allies = 9, width = 24, height = 24),
        stage("legacy_stage_243", initialUnits = 36, enemies = 33, allies = 0, width = 28, height = 22),
        stage("legacy_stage_244", initialUnits = 36, enemies = 33, allies = 0, width = 40, height = 40),
        stage("legacy_stage_245", initialUnits = 60, enemies = 57, allies = 0, width = 32, height = 22),
        stage("legacy_stage_249", initialUnits = 10, enemies = 7, allies = 0, width = 20, height = 22),
        stage("legacy_stage_250", initialUnits = 9, enemies = 6, allies = 0, width = 18, height = 21),
        stage("legacy_stage_251", initialUnits = 9, enemies = 6, allies = 0, width = 30, height = 24),
        stage("legacy_stage_252", initialUnits = 9, enemies = 6, allies = 0, width = 28, height = 24),
        stage("legacy_stage_257", initialUnits = 26, enemies = 20, allies = 3, width = 40, height = 40),
        stage("legacy_stage_258", initialUnits = 9, enemies = 6, allies = 0, width = 24, height = 30),
        stage("legacy_stage_259", initialUnits = 9, enemies = 6, allies = 0, width = 35, height = 30),
        stage("legacy_stage_263", initialUnits = 41, enemies = 38, allies = 0, width = 20, height = 35),
        stage("legacy_stage_264", initialUnits = 43, enemies = 20, allies = 20, width = 32, height = 26),
        stage("legacy_stage_265", initialUnits = 23, enemies = 20, allies = 0, width = 32, height = 22),
        stage(
            "legacy_stage_266",
            initialUnits = 39,
            enemies = 36,
            allies = 0,
            width = 30,
            height = 22,
            protectUnits = listOf("hero_3"),
        ),
        stage("legacy_stage_268", initialUnits = 65, enemies = 61, allies = 1, width = 32, height = 30),
        stage("legacy_stage_269", initialUnits = 42, enemies = 35, allies = 4, width = 30, height = 24),
        stage("legacy_stage_272", initialUnits = 17, enemies = 14, allies = 0, width = 24, height = 26),
        stage("legacy_stage_276", initialUnits = 23, enemies = 13, allies = 7, width = 36, height = 36),
        stage("legacy_stage_277", initialUnits = 53, enemies = 36, allies = 14, width = 26, height = 26),
        stage(
            "legacy_stage_279",
            initialUnits = 47,
            enemies = 26,
            allies = 18,
            width = 40,
            height = 30,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_280",
            initialUnits = 13,
            enemies = 10,
            allies = 0,
            width = 24,
            height = 28,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_281",
            initialUnits = 31,
            enemies = 14,
            allies = 14,
            width = 30,
            height = 28,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_283",
            initialUnits = 44,
            enemies = 31,
            allies = 10,
            width = 36,
            height = 32,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_285", initialUnits = 24, enemies = 13, allies = 8, width = 30, height = 30),
        stage("legacy_stage_287", initialUnits = 12, enemies = 9, allies = 0, width = 30, height = 24),
        stage("legacy_stage_288", initialUnits = 38, enemies = 28, allies = 7, width = 30, height = 35),
        stage("legacy_stage_293", initialUnits = 37, enemies = 34, allies = 0, width = 35, height = 30),
        stage("legacy_stage_295", initialUnits = 43, enemies = 38, allies = 2, width = 25, height = 36),
        stage("legacy_stage_297", initialUnits = 14, enemies = 11, allies = 0, width = 32, height = 24),
        stage("legacy_stage_298", initialUnits = 7, enemies = 4, allies = 0, width = 31, height = 19),
        stage("legacy_stage_299", initialUnits = 10, enemies = 7, allies = 0, width = 32, height = 25),
        stage(
            "legacy_stage_300",
            initialUnits = 44,
            enemies = 41,
            allies = 0,
            width = 30,
            height = 30,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_301", initialUnits = 27, enemies = 24, allies = 0, width = 35, height = 35),
        stage(
            "legacy_stage_302",
            initialUnits = 35,
            enemies = 29,
            allies = 3,
            width = 40,
            height = 19,
            protectUnits = listOf("hero_3"),
        ),
        stage(
            "legacy_stage_309",
            initialUnits = 41,
            enemies = 38,
            allies = 0,
            width = 38,
            height = 28,
            protectUnits = listOf("hero_2"),
        ),
        stage(
            "legacy_stage_310",
            initialUnits = 30,
            enemies = 27,
            allies = 0,
            width = 38,
            height = 28,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_311", initialUnits = 39, enemies = 36, allies = 0, width = 40, height = 40),
        stage(
            "legacy_stage_312",
            initialUnits = 49,
            enemies = 46,
            allies = 0,
            width = 34,
            height = 38,
            protectUnits = listOf("hero_2"),
        ),
        stage("legacy_stage_313", initialUnits = 45, enemies = 42, allies = 0, width = 36, height = 33),
        stage("legacy_stage_314", initialUnits = 7, enemies = 4, allies = 0, width = 30, height = 30),
        stage("legacy_stage_316", initialUnits = 19, enemies = 9, allies = 7, width = 38, height = 30),
        stage("legacy_stage_317", initialUnits = 20, enemies = 17, allies = 0, width = 36, height = 24),
        stage("legacy_stage_319", initialUnits = 43, enemies = 33, allies = 7, width = 31, height = 30),
        stage("legacy_stage_320", initialUnits = 4, enemies = 1, allies = 0, width = 36, height = 24),
        stage("legacy_stage_321", initialUnits = 14, enemies = 11, allies = 0, width = 32, height = 19),
        stage("legacy_stage_322", initialUnits = 13, enemies = 10, allies = 0, width = 30, height = 30),
        stage("legacy_stage_323", initialUnits = 4, enemies = 1, allies = 0, width = 25, height = 25),
        stage("legacy_stage_325", initialUnits = 13, enemies = 10, allies = 0, width = 30, height = 22),
        stage("legacy_stage_326", initialUnits = 14, enemies = 10, allies = 1, width = 31, height = 40),
        stage("legacy_stage_327", initialUnits = 51, enemies = 48, allies = 0, width = 31, height = 40),
        stage("legacy_stage_328", initialUnits = 8, enemies = 4, allies = 1, width = 36, height = 30),
        stage("legacy_stage_329", initialUnits = 10, enemies = 7, allies = 0, width = 32, height = 30),
        stage("legacy_stage_330", initialUnits = 29, enemies = 24, allies = 2, width = 30, height = 29),
        stage("legacy_stage_331", initialUnits = 17, enemies = 5, allies = 9, width = 30, height = 29),
        stage("legacy_stage_332", initialUnits = 12, enemies = 9, allies = 0, width = 36, height = 30),
        stage("legacy_stage_333", initialUnits = 26, enemies = 3, allies = 20, width = 36, height = 35),
        stage("legacy_stage_334", initialUnits = 33, enemies = 24, allies = 6, width = 27, height = 26),
        stage("legacy_stage_335", initialUnits = 13, enemies = 9, allies = 1, width = 30, height = 19),
        stage("legacy_stage_336", initialUnits = 30, enemies = 18, allies = 9, width = 36, height = 22),
        stage("legacy_stage_338", initialUnits = 20, enemies = 17, allies = 0, width = 36, height = 24),
        stage("legacy_stage_339", initialUnits = 15, enemies = 12, allies = 0, width = 28, height = 26),
        stage("legacy_stage_340", initialUnits = 15, enemies = 12, allies = 0, width = 34, height = 26),
        stage("legacy_stage_341", initialUnits = 33, enemies = 23, allies = 7, width = 30, height = 24),
        stage("legacy_stage_343", initialUnits = 63, enemies = 59, allies = 1, width = 40, height = 35),
        stage("legacy_stage_344", initialUnits = 64, enemies = 61, allies = 0, width = 35, height = 30),
        stage("legacy_stage_345", initialUnits = 17, enemies = 10, allies = 4, width = 30, height = 30),
        stage("legacy_stage_347", initialUnits = 20, enemies = 3, allies = 14, width = 35, height = 25),
        stage("legacy_stage_351", initialUnits = 17, enemies = 10, allies = 4, width = 40, height = 40),
        stage("legacy_stage_352", initialUnits = 5, enemies = 1, allies = 1, width = 40, height = 36),
        stage("legacy_stage_353", initialUnits = 5, enemies = 1, allies = 1, width = 40, height = 40),
        stage("legacy_stage_354", initialUnits = 19, enemies = 1, allies = 15, width = 38, height = 38),
        stage("legacy_stage_355", initialUnits = 82, enemies = 69, allies = 10, width = 40, height = 40),
        stage("legacy_stage_356", initialUnits = 64, enemies = 43, allies = 18, width = 40, height = 40),
        stage("legacy_stage_357", initialUnits = 55, enemies = 40, allies = 12, width = 40, height = 40),
    )

    val initialUnitsByStageId: Map<String, Int> = all.associate { it.stageId to it.initialUnits }

    private fun stage(
        stageId: String,
        initialUnits: Int,
        enemies: Int,
        allies: Int,
        width: Int,
        height: Int,
        deferred: Int = 0,
        protectUnits: List<String> = listOf("hero_1"),
        minTerrainKinds: Int = 2,
    ): PromotedStageExpectation =
        PromotedStageExpectation(
            runtime = requireNotNull(PromotedStageRuntimes.all().singleOrNull { it.stageId == stageId }),
            initialUnits = initialUnits,
            enemies = enemies,
            allies = allies,
            width = width,
            height = height,
            deferred = deferred,
            protectUnits = protectUnits,
            minTerrainKinds = minTerrainKinds,
        )
}
